# Generated by Django 3.2.18 on 2023-05-26 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mainfunc.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dataset', models.CharField(default='', max_length=50)),
                ('label_name', models.CharField(default='', max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=mainfunc.models.image_upload_path)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainfunc.label')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('learning_time', models.CharField(default='', max_length=10)),
                ('accuracy', models.CharField(default='', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to=mainfunc.models.image_upload_path)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
