# Generated by Django 3.2.18 on 2023-06-03 15:55

from django.db import migrations, models
import mainfunc.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainfunc', '0002_model_dataset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='dataset',
        ),
        migrations.AlterField(
            model_name='model',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=mainfunc.models.model_upload_path),
        ),
    ]
